### ISSUE TITLE
When I try to run python train.py 1，encountered a problem

### ISSUE THREAD

**Issue by yaoyaoyao13** [HuiZhang0812/DiffusionAD#14]
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0
how to solve this problem?

**Comment by HuiZhang0812** [comment]
I haven't encountered this problem before. Could you provide more detailed error information?

**Comment by yaoyaoyao13** [comment]
I only modified the mvtec in the args1.json file_ Root_ Path, arbitrarily_ Source_ Path and output_ Path, and Foreground was added to the mvtec dataset based on the data tree
<img width="879" alt="068a725151c6038689e37662e597d56" src="https://github.com/HuiZhang0812/DiffusionAD/assets/143946108/35e80c1e-df15-45e7-aee2-031765e7598f">

**Comment by HuiZhang0812** [comment]
The anomaly source path refers to the Describable Textures dataset. Please download it and then modify the anomaly source path.

**Comment by yaoyaoyao13** [comment]
Thank you for your reply. I think I have modified the code according to your requirements, but it is not




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuiZhang0812/DiffusionAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuiZhang0812/DiffusionAD] When I try to run python train.py 1，encountered a problem (Issue #14)





 
The anomaly source path refers to the Describable Textures dataset. Please download it and then modify the anomaly source path.

**Comment by yaoyaoyao13** [comment]
Thank you for your reply. I think I have modified the code according to your requirements, but it is not
<img width="879" alt="400f2455addaa4c702486d68938f9bd" src="https://github.com/HuiZhang0812/DiffusionAD/assets/143946108/13b056c5-c39d-40bb-a102-d1bea07db784">

**Comment by HuiZhang0812** [comment]
We only utilized the "images" folder within the DTD directory. I have updated the source code for convenience and you can re-download it.​

**Comment by yaoyaoyao13** [comment]
Thank you, my problem has been resolved

**Comment by 02lenny** [comment]
Hello! @yaoyaoyao13 

May I ask what did you do to solve the problem? I am also encountering this problem and this is my path to the DTD /content/drive/MyDrive/DiffusionDA/DiffusionAD-main/datasets/DTD

and the folders inside this are the folders from images, here is an example: /content/drive/MyDrive/DiffusionDA/DiffusionAD-main/datasets/DTD/banded

thank you so much for answering as I am trying to implement this research for school.
