### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Airbyj92** [HuiZhang0812/DiffusionAD#15]
按要求修改了mvtec_root_path、anomaly_source_path、output_path训练还是会报错，而且在您给出的数据结构中MVTec-AD数据集中carpet类别里的thresh在数据集中未找到

**Comment by Ace-blue** [comment]
It has been upload on the[Google Drive](https://drive.google.com/drive/folders/1goH-PqWD35jvXuZNcBlR6elKf7eBx8lY?usp=drive_link) in README.

**Comment by Ace-blue** [comment]
> 按要求修改了mvtec_root_path、anomaly_source_path、output_path训练还是会报错，而且在您给出的数据结构中MVTec-AD数据集中carpet类别里的thresh在数据集中未找到

It has been upload on the[Google Drive](https://drive.google.com/drive/folders/1goH-PqWD35jvXuZNcBlR6elKf7eBx8lY?usp=drive_link) in README.
