### ISSUE TITLE
Experiment on MVTec LOCO

### ISSUE THREAD

**Issue by Ace-blue** [HuiZhang0812/DiffusionAD#17]
Dear @HuiZhang0812 , your work is amazing.
Now I want to try [DiffusionAD](https://github.com/HuiZhang0812/DiffusionAD) on dataset MVTec LOCO.
But I donot know if your method can work on this dataset.
Have your team ever tried this dataset?
Any suggestions for me if I want try?

Thanks for your reply ^-^

**Comment by HuiZhang0812** [comment]
I have not yet tried the MVTec LOCO dataset. However, I believe that for any dataset, as long as you design a suitable anomaly synthetic strategy (such as object foreground, etc.), DiffusionAD can be deployed.

**Comment by Airbyj92** [comment]
请问thresh子文件夹中的png图片是正样本的二值图吗

**Comment by Airbyj92** [comment]
Is the png image in the thresh subfolder a binary graph of the positive sample in training?

**Comment by HuiZhang0812** [comment]
> Is the png image in the thresh subfolder a binary graph of the positive sample in training?

yes!

**Comment by Airbyj92** [comment]
> > thresh 子文件夹中的 png 图像是训练中阳性样本的二进制图吗？
> 
> 是的！

Hello, I use 4090 inference speed of 550 ms/piece please ask the speed can also be increased

**Comment by HuiZhang0812** [comment]
> > > thresh 子文件夹中的 png 图像是训练中阳性样本的二进制图吗？
> > 
> > 
> > 是的！
> 
> Hello, I use 4090 inference speed of 550 ms/piece please ask the speed can also be increased

Does the inference time you calculated include the computation time for metrics like Pro?

**Comment by Airbyj92** [comment]
> > > > thresh 子文件夹中的 png 图像是训练中阳性样本的二进制图吗？
> > > 
> > > 
> > > 是的！
> > 
> > 
> > 您好，我使用4090推理速度为550毫秒/件，请询问速度也可以提高
> 
> 您计算的推理时间是否包括 Pro 等指标的计算时间？

Using your original prediction code

**Comment by HuiZhang0812** [comment]
The eval.py script does not involve the calculation of frames per second (FPS) yet. Inference speed varies across different GPUs, and I believe that computation time for performance metrics should not be included when calculating inference time. How did you obtain the 550 ms/piece inference speed?​

**Comment by HuiZhang0812** [comment]
> > > > > thresh 子文件夹中的 png 图像是训练中阳性样本的二进制图吗？
> > > > 
> > > > 
> > > > 是的！
> > > 
> > > 
> > > 您好，我使用4090推理速度为550毫秒/件，请询问速度也可以提高
> > 
> > 
> > 您计算的推理时间是否包括 Pro 等指标的计算时间？
> 
> Using your original prediction code

The eval.py script does not involve the calculation of frames per second (FPS) yet. Inference speed varies across different GPUs, and I believe that computation time for performance metrics should not be included when calculating inference time. How did you obtain the 550 ms/piece inference speed?​

**Comment by Airbyj92** [comment]
> > > > > > thresh 子文件夹中的 png 图像是训练中阳性样本的二进制图吗？
> > > > > 
> > > > > 
> > > > > 是的！
> > > > 
> > > > 
> > > > 您好，我使用4090推理速度为550毫秒/件，请询问速度也可以提高
> > > 
> > > 
> > > 您计算的推理时间是否包括 Pro 等指标的计算时间？
> > 
> > 
> > Using your original prediction code
> 
> The eval.py script does not involve the calculation of frames per second (FPS) yet. Inference speed varies across different GPUs, and I believe that computation time for performance metrics should not be included when calculating inference time. How did you obtain the 550 ms/piece inference speed?​

There will be a rate of inference per second, but there should be some metric calculation mixed in

**Comment by HU13-SVG** [comment]
Have the experiments on the LOCO dataset been completed?
