### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Airbyj92** [HuiZhang0812/DiffusionAD#18]
Hello, I reported the error at the end of the training. The following is the error content
![屏幕截图 2023-12-12 163430](https://github.com/HuiZhang0812/DiffusionAD/assets/149363229/ae20409a-3d18-44fb-82fb-352884fe9bd7)

**Comment by HuiZhang0812** [comment]
This looks like an issue with the dataset path.

**Comment by Airbyj92** [comment]
> This looks like an issue with the dataset path.

There was no problem in the previous training, and this problem only appeared after the last round of training. I have verified the model and it seems that there is no impact. Have you ever encountered such a problem

**Comment by HuiZhang0812** [comment]
Hello, I have double-checked the code, and I did not encounter such a problem. Maybe you can download the source code again and give it another try.

**Comment by Airbyj92** [comment]
Okay, thank you

**Comment by Airbyj92** [comment]
Using your newly uploaded code found that there is still this error
