### ISSUE TITLE
The role of thresh

### ISSUE THREAD

**Issue by Airbyj92** [HuiZhang0812/DiffusionAD#21]
Hello, what is the role of "thresh" in the training set in this project, and what should we pay attention to when making "thresh" samples?

**Comment by Airbyj92** [comment]
Is there any way to contact you faster? Would you like to discuss some questions with you

**Comment by HuiZhang0812** [comment]
Thresh refers to the object foreground. I will respond to your questions as soon as possible :)

**Comment by Airbyj92** [comment]
Ok, thank you for your trouble. Looking forward to your reply
