### ISSUE TITLE
Should we have a thresh directory in datasets?

### ISSUE THREAD

**Issue by azadfatemeh** [HuiZhang0812/DiffusionAD#22]
Hello, 
I have seen this line of code in the class dataset_beta_thresh.py : 'self.textural_foreground_path = sorted(glob.glob(foreground_path +"/thread/*.png"))' but since textural_foreground_path is 0 all the time I doubted whether the 'thread' is right or not. because I don't have such a directory, shouldn't it be 'thresh' instead?

**Comment by HuiZhang0812** [comment]
It should be the 'thresh' folder, and in dataset_beta_thresh.py, the line 'self.textural_foreground_path = sorted(glob.glob(foreground_path +"/thresh/*.png"))' also references the 'thresh' folder. I'm a bit confused, where is the 'thread' ?

**Comment by azadfatemeh** [comment]
It was my mistake
