### ISSUE TITLE
loss nan  for distributed deep learning 

### ISSUE THREAD

**Issue by cclamd** [HuiZhang0812/DiffusionAD#33]
hi , @HuiZhang0812 , 

> https://github.com/HuiZhang0812/DiffusionAD/issues/26

 there is no A100(80G) for me ,and i trained the model using six 3090 cards  for distributed deep learning ,but find loss is alse nan ! so does it decrease for distributed deep learning ?
![屏幕截图 2024-01-31 144712](https://github.com/HuiZhang0812/DiffusionAD/assets/19679120/8d6f42a8-e445-4157-b170-ec572164d220)

best regards!

**Comment by HuiZhang0812** [comment]
When the batch size is small, it may lead to an entire batch consisting solely of abnormal samples, thereby affecting the calculation of the paper's loss formula (Formula 9).  We have fixed this. We have fixed this bug. Please try again.
