### ISSUE TITLE
这是一项非常有前景的工作。我有一个疑问需要请教您？

### ISSUE THREAD

**Issue by sxq1004** [HuiZhang0812/DiffusionAD#35]
这是一项非常有前景的工作。我有一个疑问需要请教您？
在去噪过程使用的一步式去噪范式，那么在正向加噪模拟扩散过程也同样是一步加噪吗？也就是说两个正向扩散训练过程中都只需要扩散一次，xts是直接从t=0一步加噪到ts来学习ϵθ(xts)，xtb是直接从t=0一步加噪到tb来学习ϵθ(xtb)。请问是我现在理解的意思吗？期待您的解惑，谢谢！

**Comment by HuiZhang0812** [comment]
问题1:我们使用的标准的扩散模型的前向过程，它是一步加噪的。
问题2:是的，对输入图像的两种尺度的加噪是独立的。

Question 1: We utilize the standard forward process of the diffusion model, which is a closed form (eq.1 ).
Question 2: Yes, the two scales perturbation of the input image is independent.
