### ISSUE TITLE
我的電腦batchsize只能設到3 其他地方要怎麼設定才能表現很好呢 我是用visa資料集

### ISSUE THREAD

**Issue by henrychou1233** [HuiZhang0812/DiffusionAD#36]
{
  "img_size": [256,256],
  "Batch_Size": 3,
  "EPOCHS": 100,
  "T": 1000,
  "base_channels": 128,
  "beta_schedule": "cosine",
  "loss_type": "l2",
  "diffusion_lr": 1e-10,
  "seg_lr": 1e-5,
  "random_slice": true,
  "weight_decay": 0.0,
  "save_imgs":true,
  "save_vids":false, 
  "dropout":0,
  "attention_resolutions":"32,16,8",
  "num_heads":8,
  "num_head_channels":-1,
  "noise_fn":"gauss",
  "channels":3,
  "visa_root_path":"/home/anywhere3090l/Desktop/henry/DiffusionAD-main/visa",
  "anomaly_source_path":"/home/anywhere3090l/Desktop/henry/DiffusionAD-main/dtd",
  "noisier_t_range":600,
  "less_t_range":300,
  "condition_w":5,
  "eval_normal_t":200,
  "eval_noisier_t":400,
  "output_path":"outputs"

}

**Comment by HuiZhang0812** [comment]
You only need to modify the batch size and keep other settings unchanged.
