### ISSUE TITLE
a question about syntheticanomalies

### ISSUE THREAD

**Issue by wyhlovecpp** [HuiZhang0812/DiffusionAD#37]
In paper, you say that you will get a **pre-segmentation result F** at first. But I don't find it in your code. Looking forward to your reply!
![image](https://github.com/HuiZhang0812/DiffusionAD/assets/73157596/d7d25f7d-f513-46c5-977c-1c67993b8a48)

**Comment by HuiZhang0812** [comment]
As mentioned in the "[README.md](https://github.com/HuiZhang0812/DiffusionAD/blob/main/README.md)" file under the section "[Foreground](https://github.com/HuiZhang0812/DiffusionAD?tab=readme-ov-file#foreground)": For the object dataset, we use [DIS](https://github.com/xuebinqin/DIS) to extract foregrounds. For the textural dataset, we define the foreground as a randomly selected portion of the entire image. Images of these foregrounds can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1goH-PqWD35jvXuZNcBlR6elKf7eBx8lY?usp=drive_link).
