### ISSUE TITLE
Hello, what can be input to self.textural_foreground_path

### ISSUE THREAD

**Issue by caihaocong** [HuiZhang0812/DiffusionAD#38]
Hello，I read the codes.  and I want to train only the mvtec dataset，but I don't know what can be input to the path of "foreground_path +'/thresh'"， is the ground_truth pictures?

"self.textural_foreground_path = sorted(glob.glob(foreground_path +"/thresh/*.png"))"

Thank you!

**Comment by HuiZhang0812** [comment]
Hello, Images of these foregrounds can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1goH-PqWD35jvXuZNcBlR6elKf7eBx8lY?usp=drive_link) and then puts them in the corresponding path following the data tree.

**Comment by caihaocong** [comment]
Thank you!
