### ISSUE TITLE
Why is recon_con still a noisy image?

### ISSUE THREAD

**Issue by boxbox2** [HuiZhang0812/DiffusionAD#39]
![image](https://github.com/HuiZhang0812/DiffusionAD/assets/56194614/9e36c9e0-1533-44f0-bbc4-785a860bdd6a)

**Comment by HuiZhang0812** [comment]
May I ask how many epochs did you train for?

**Comment by boxbox2** [comment]
> May I ask how many epochs did you train for?

3000 train epoch
I use the args1 argument you gave but training_dataset_loader  i set batch_size = 6,nums_workers = 8
and I trained only the carpet categories in the mvtec dataset
{
  "img_size": [256,256],
  "Batch_Size": 6,
  "EPOCHS": 3000,
  "T": 1000,
  "base_channels": 128,
  "beta_schedule": "linear",
  "loss_type": "l2",
  "diffusion_lr": 1e-4,
  "seg_lr": 1e-5,
  "random_slice": true,
  "weight_decay": 0.0,
  "save_imgs":true,
  "save_vids":false, 
  "dropout":0,
  "attention_resolutions":"32,16,8",
  "num_heads":4,
  "num_head_channels":-1,
  "noise_fn":"gauss",
  "channels":3,
  "mvtec_root_path":"datasets/mvtec",
  "visa_root_path":"datasets/VisA/visa",
  "dagm_root_path":"datasets/dagm",
  "mpdd_root_path":"datasets/mpdd",
  "anomaly_source_path":"datasets/dtd",
  "noisier_t_range":600,
  "less_t_range":300,
  "condition_w":1,
  "eval_normal_t":200,
  "eval_noisier_t":400,
  "output_path":"outputs"

}

**Comment by HuiZhang0812** [comment]
Which "checkpoint_type" are you using in eval.py?

**Comment by boxbox2** [comment]
> Which "checkpoint_type" are you using in eval.py?

best

**Comment by HuiZhang0812** [comment]
Try it with "checkpoint_type=last".

**Comment by boxbox2** [comment]
> Try it with "checkpoint_type=last".

![image](https://github.com/HuiZhang0812/DiffusionAD/assets/56194614/3f50113d-6ef9-4019-a475-eecacf886779)
It's the same as the original

**Comment by HuiZhang0812** [comment]
Have you recorded the loss curve?

**Comment by boxbox2** [comment]
> Have you recorded the loss curve?

I haven't done anything special. I just ran the cloned code step by step. After running train.py, I ran eval.py

**Comment by HuiZhang0812** [comment]
I will run your config to verify, thank you for your patience. By the way, I found that the results in #40  were as expected.

**Comment by fatemeh-azad** [comment]
I also have the same problem, did you find any solution for that?

**Comment by boxbox2** [comment]
> I also have the same problem, did you find any solution for that?

not yet

**Comment by HuiZhang0812** [comment]
Thank you for your patience. We used the same configuration as yours, and our reconstruction and segmentation results were accurate. 
![thread_000](https://github.com/HuiZhang0812/DiffusionAD/assets/44562591/ca4d5531-221f-4935-abeb-60e716c8c2b4)

May I ask if you are using the latest code? We recently released an update that fixes the issue of loss becoming "nan" when the batch size is small. Could you please try our latest code again?

**Comment by boxbox2** [comment]
> Thank you for your patience. We used the same configuration as yours, and our reconstruction and segmentation results were accurate. ![thread_000](https://private-user-images.githubusercontent.com/44562591/310555582-ca4d5531-221f-4935-abeb-60e716c8c2b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTE1MTgsIm5iZiI6MTcwOTc5MTIxOCwicGF0aCI6Ii80NDU2MjU5MS8zMTA1NTU1ODItY2E0ZDU1MzEtMjIxZi00OTM1LWFiZWItNjBlNzE2YzhjMmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2MDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YmYxNTI5MjkyYmQxMDJjM2Y1MTNjNDE3OWRlYmViMjllYmJkZmE1NGJlZmQyZmRiNWZhMjgxYjIxMTE4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyzSvjoi-vWYqn5vGqCvuLimFHTyllBVkOtHb8sMlgw)
> 
> May I ask if you are using the latest code? We recently released an update that fixes the issue of loss becoming "nan" when the batch size is small. Could you please try our latest code again?

Thank you for your reply. I did indeed use skipping method to handle NaN values before. I will re-download your updated code for experimentation. Thanks again for your patient response.

**Comment by fatemeh-azad** [comment]
> Thank you for your patience. We used the same configuration as yours, and our reconstruction and segmentation results were accurate. ![thread_000](https://private-user-images.githubusercontent.com/44562591/310555582-ca4d5531-221f-4935-abeb-60e716c8c2b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTU5NjMsIm5iZiI6MTcwOTgxNTY2MywicGF0aCI6Ii80NDU2MjU5MS8zMTA1NTU1ODItY2E0ZDU1MzEtMjIxZi00OTM1LWFiZWItNjBlNzE2YzhjMmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEyNDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMzM5ZTUyZTRmNGIxZWVmY2M1MzI5ZTM3ZGRjYWE3YTJlY2IyNzczNTA1ZWExNTk4NzAzZDlkMzVkZjQxYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezQezSOAA_9vD89FrcFRXSZlDybIyjWs3OrwFX3PgQc)
> 
> May I ask if you are using the latest code? We recently released an update that fixes the issue of loss becoming "nan" when the batch size is small. Could you please try our latest code again?

Thanks for your prompt reply. My problem is solved now. Since I did not use the dataset you provided, I had some mistakes in normalization that may lead to this problem.
