### ISSUE TITLE
Hello, a question about image score

### ISSUE THREAD

**Issue by caihaocong** [HuiZhang0812/DiffusionAD#40]
Hello, thank you for your open-source code. I train the dataset of the MvTecAD. I get the good performance of the anomaly images. but when I test the normal images, the image score is low but some region of the heatmap is high. What is the relationship between the  image score and heatmap? How can I to reduce high heatmap of the normal images?

![DiffisionAD实验记录_001](https://github.com/HuiZhang0812/DiffusionAD/assets/8640352/2e95f934-dd53-4606-b7b8-23cc0a08f0e7)

**Comment by HuiZhang0812** [comment]
Maybe you can adjust "min_max_norm" and "gaussian_filter" in eval.py.

**Comment by caihaocong** [comment]
> Maybe you can adjust "min_max_norm" and "gaussian_filter" in eval.py.

Yes, that is right.  Thank you very much !
Next, we will try to accelerate the inference speed of the model.
