### ISSUE TITLE
Hello, a question about "img_size"

### ISSUE THREAD

**Issue by caihaocong** [HuiZhang0812/DiffusionAD#43]
Hello, Zhanghui, thank you for your open-source code.   

I have a question about the parameter of "img_size".  How can I change  "img_size": [256,256] to  "img_size": [1060,1060], or  "img_size": [1024,1024] ?   Do I need to modify the original model? Can you give me some suggestions?

**Comment by HuiZhang0812** [comment]
Hello, you can modify "img_size" in args1.json.

**Comment by caihaocong** [comment]
Thank you for your reply.

“        if channel_mults == "":
            if img_size == 512:
                channel_mults = (0.5, 1, 1, 2, 2, 4, 4)
            elif img_size == 256:   # 默认参数
                channel_mults = (1, 1, 2, 2, 4, 4)
            elif img_size == 128:
                channel_mults = (1, 1, 2, 3, 4)
            elif img_size == 64:
                channel_mults = (1, 2, 3, 4)
            elif img_size == 32:
                channel_mults = (1, 2, 3, 4)
            else:
                raise ValueError(f"unsupported image size: {img_size}") ”

hello，is the large size 512 ?  How to change it to "img_size": [1060,1060]?

**Comment by HuiZhang0812** [comment]
Sorry, I haven't tried such a large image size. I think you might try resizing the image size, considering that larger images will bring greater training overhead.

**Comment by caihaocong** [comment]
Thank you very much.  But I need to detect particularly tiny defects. I will try another solution.

**Comment by HuiZhang0812** [comment]
Okay, here is a suggestion that you might consider: patchfy the image, for example, divide the 1024*1024 image into 4 512*512 images, and then perform training and inference.

**Comment by caihaocong** [comment]
Ok，thanks a lot.
