### ISSUE TITLE
训练化纤数据集

### ISSUE THREAD

**Issue by isyzwang** [HuiZhang0812/DiffusionAD#44]
你好我想问一下，如果想利用如下的化纤异常数据集进行测试，我该如何微调参数或模型来提高效果呢？时间步长设置为1000是默认为最佳效果吗？
![2023-03-25_15-34-15-1373_camera2_1_0](https://github.com/HuiZhang0812/DiffusionAD/assets/130199146/30e35a8c-57f0-46a2-9877-9a218583afd5)
![d_0000250_2023-07-03-14-35-27_camera00_1_0](https://github.com/HuiZhang0812/DiffusionAD/assets/130199146/39ed4d23-a8f3-4919-a084-75e961724a38)
![d_0012000_2023-04-25-18-41-21_camera01_3_0](https://github.com/HuiZhang0812/DiffusionAD/assets/130199146/6b79674e-5a9d-46be-b84e-3faff427e307)
![d_0000500_2023-07-26-17-06-04_camera01_0_0](https://github.com/HuiZhang0812/DiffusionAD/assets/130199146/564247e6-49d7-495d-998c-3c034bfa8b2b)

**Comment by HuiZhang0812** [comment]
Hello, I don't think there is any need to modify the training parameters.

你好，我觉得无需修改训练参数。
