### ISSUE TITLE
数据集中的thresh是什么意思

### ISSUE THREAD

**Issue by zty292** [HuiZhang0812/DiffusionAD#45]
数据集中的thresh这个文件夹是什么，为什么我下载的官方mvtecAD数据集中没有这个文件夹

**Comment by HuiZhang0812** [comment]
Thresh refers to the foreground of the object, used for the generation of synthetic anomaly. See section 4.4 of the paper for more details. The thresh can be downloaded [here](https://drive.google.com/drive/folders/1goH-PqWD35jvXuZNcBlR6elKf7eBx8lY?usp=drive_link).
