### ISSUE TITLE
Checkpoints for VisA dataset

### ISSUE THREAD

**Issue by alex-costanzino** [HuiZhang0812/DiffusionAD#46]
Hi! First of all, thank you very much for sharing this fascinating work.

I was wondering whether you were planning to release the checkpoints of the trained models for (at least) the VisA dataset.
I would like to re-evaluate this work with another protocol to insert it into a benchmark, so to be as fair as possible with your results I would prefer to have the original weights.

Thank you again!

**Comment by HuiZhang0812** [comment]
Hi, thanks for recognizing our work. We may plan to upload checkpoints in the future.
