### ISSUE TITLE
模擬異常被用在哪邊

### ISSUE THREAD

**Issue by henrychou1233** [HuiZhang0812/DiffusionAD#47]
用正常樣本加上DTD模擬異常 
有被放到訓練中嗎

因為DIFFUSION MODEL不是訓練只能是正常的
輸入異常會只能生出正常照片
算兩張照片的距離

我不懂模擬異常被用在哪邊
謝謝您

**Comment by HuiZhang0812** [comment]
The synthetic anomalies are used to train the segmentation network. See Equations 9 and 10 for details.
