### ISSUE TITLE
训练与推理时间

### ISSUE THREAD

**Issue by yuki1ssad** [HuiZhang0812/DiffusionAD#49]
您好，请问可否告知硬件配置及相应的训练时长与推理速度？谢谢！

**Comment by Super-mylife** [comment]
> 您好，请问可否告知硬件配置及相应的训练时长与推理速度？谢谢！

您好您有尝试嘛 我初步训练了一下单卡24gb下只能跑最大3batch 跑完可能需要半个月...

**Comment by HuiZhang0812** [comment]
We trained on A100 80g, and the average training time was about 16 hours.

**Comment by caihaocong** [comment]
可以修改参数，缩小模型，例如: base_channel，实际不需要那么大的模型也能有不错的效果的
