### ISSUE TITLE
about dataset_beta_thresh.py and def perlin_synthetic

### ISSUE THREAD

**Issue by boxbox2** [HuiZhang0812/DiffusionAD#53]
"In this part, I noticed that `perlin_synthetic` seems to apply `randAugmenter` to `anomaly_img`, but the corresponding mask does not go through `randAugmenter`. Is this correct?"

So the mask and the corresponding composite image can still be correctly matched?
![image](https://github.com/HuiZhang0812/DiffusionAD/assets/56194614/c59cc25c-0fb3-4dac-852c-ccf157734f88)

**Comment by HuiZhang0812** [comment]
The `perlin_synthetic` is able to synthesize the correct abnormal image. The `randAugmenter` is used to synthesize the abnormal appearance. After that, the mask extracts the corresponding area and combines it with the normal image to synthesize the abnormal image.
