### ISSUE TITLE
The trained loss is nan

### ISSUE THREAD

**Issue by Airbyj92** [HuiZhang0812/DiffusionAD#56]
![屏幕截图 2024-10-28 172137](https://github.com/user-attachments/assets/5002612e-106c-457b-a2fc-16a80f440fbd)

**Comment by HuiZhang0812** [comment]
Please see https://github.com/HuiZhang0812/DiffusionAD/issues/29 for more details. This problem has been solved in our latest code.

**Comment by Airbyj92** [comment]
> 请参阅 #29 了解更多详情。这个问题在我们的最新代码中已经解决了。

thank you
