### ISSUE TITLE
about image-auroc

### ISSUE THREAD

**Issue by boxbox2** [HuiZhang0812/DiffusionAD#57]
Hi,When I look at the ```dataset_beta_thresh.py```, I find that sometimes it is not enhanced.
```    
def perlin_synthetic(self, image, thresh, anomaly_source_path, cv2_image,thresh_path):
        no_anomaly = torch.rand(1).numpy()[0]
        if no_anomaly > 0.5:
            image = image.astype(np.float32)
            return image, np.zeros((self.resize_shape[0], self.resize_shape[1], 1), dtype=np.float32), np.array([0.0], dtype=np.float32)
```
But from the code in other articles, it's almost 100% likely to generate exceptions during the training phase. I tried to use your data processing (i.e. 50% synthesis anomaly, 50% non synthesis) and found that it would cause a slight decrease in Image AUROC. Are you concerned about this possibility?

**Comment by HuiZhang0812** [comment]
It depends on the situation. In our paper, both normal data and abnormal data are required during training.

**Comment by boxbox2** [comment]
> It depends on the situation. In our paper, both normal data and abnormal data are required during training.


Thank you for your patient reply
